config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders
  resources :trucks
  resources :empleados
  resources :empresas
  resources :contactos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contacto.rb
class Contacto < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  has_many :evaluation
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/empresa.rb
class Empresa < ApplicationRecord
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
	validates :date, presence: true
  belongs_to :customer, optional: true
  has_one :evaluation
  belongs_to :truck, optional: true
end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
	def index
		@contactos = Contacto.all
	end

	def new
		@contacto = Contacto.new
	end

	def edit
		@contacto = Contacto.find params[:id]
	end

	def create
		@contacto = Contacto.new
		@contacto.nombre = params[:contacto][:nombre]
		@contacto.apellido = params[:contacto][:apellido]
		@contacto.telefono = params[:contacto][:telefono]
		@contacto.correoElectronico = params[:contacto][:correoElectronico]
		@contacto.direccion = params[:contacto][:direccion]

		if @contacto.save
      flash[:notice] = "contacto creado "+ @contacto.nombre
			redirect_to contactos_path
		else
			render :new
		end
	end

	def update
		@contacto = Contacto.find params[:id]
		@contacto.nombre = params[:contacto][:nombre]
		@contacto.apellido = params[:contacto][:apellido]
		@contacto.telefono = params[:contacto][:telefono]
		@contacto.correoElectronico = params[:contacto][:correoElectronico]
		@contacto.direccion = params[:contacto][:direccion]

		if @contacto.save
      flash[:notice] = "contacto actualizado " + @contacto.nombre
			redirect_to contactos_path
		else
			render :edit
		end
	end

end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
	def index
		@empleados = Empleado.all
	end

	def new
		@empleado = Empleado.new
	end

	def edit
		@empleado = Empleado.find params[:id]
	end

	def create
		@empleado = Empleado.new
		@empleado.nombre = params[:empleado][:nombre]
		@empleado.apellido = params[:empleado][:apellido]
		@empleado.genero = params[:empleado][:genero]
		@empleado.telefono = params[:empleado][:telefono]
		@empleado.numeroDocumento = params[:empleado][:numeroDocumento]

		if @empleado.save
			flash[:notice] = "empleado creado " +@empleado.nombre
			redirect_to empleados_path
		else
			render :new
		end
	end

	def update
		@empleado = Empleado.find params[:id]
		@empleado.nombre = params[:empleado][:nombre]
		@empleado.apellido = params[:empleado][:apellido]
		@empleado.genero = params[:empleado][:genero]
		@empleado.telefono = params[:empleado][:telefono]
		@empleado.numeroDocumento = params[:empleado][:numeroDocumento]
		if @empleado.save
			flash[:notice] = "empleado actualizado" + @empleado.nombre
			redirect_to empleados_path
		else
			render :edit
		end
	end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  def index
    @empresas = Empresa.all
  end

  def new
    @empresa = Empresa.new
  end

  def edit
    @empresa = Empresa.find params[:id]
  end

  def create
    @empresa = Empresa.new
    @empresa.razonSocial = params[:empresa][:razonSocial]
    @empresa.nit = params[:empresa][:nit]
    @empresa.direccion = params[:empresa][:direccion]
    @empresa.telefono = params[:empresa][:telefono]
    @empresa.fax = params[:empresa][:fax]
    @empresa.sitioWeb = params[:empresa][:sitioWeb]

    if @empresa.save
      flash[:notice] = "empresa creada " + @empresa.razonSocial
      redirect_to empresas_path
    else
      render :new
    end
  end

  def update
    @empresa = Empresa.find params[:id]
    @empresa.razonSocial = params[:empresa][:razonSocial]
    @empresa.nit = params[:empresa][:nit]
    @empresa.direccion = params[:empresa][:direccion]
    @empresa.telefono = params[:empresa][:telefono]
    @empresa.fax = params[:empresa][:fax]
    @empresa.sitioWeb = params[:empresa][:sitioWeb]

    if @empresa.save
      flash[:notice] = "empresa actualizada " + @empresa.razonSocial
      redirect_to empresas_path
    else
      render :edit
    end
  end
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
		@orders = Order.all
	end

	def new
		#asi se crea orders
		@order = Order.new

	end

	def edit
		@order = Order.find params[:id]
	end
	def create
		#aqui los params viajan por el order
		puts "\n parametros: #{params[:order].inspect}"
		#raise "parametros"
		@order = Order.new
		@order.customer_id = params[:order][:customer_id]
		@order.truck_id = params[:order][:truck_id]
		@order.date = params[:order][:date]
		@order.distance = params[:order][:distance]
    @evaluation = @order.evaluation || @order.build_evaluation
    @evaluation.description = params[:evaluation][:description]
    @evaluation.note = params[:evaluation][:note]
    @evaluation.customer_id = @order.customer_id
		if @order.save
			flash[:notice] = "orden creada"
			redirect_to orders_path
		else
			render :new
		end
	end

	def update
		@order = Order.find params[:id]
		@order.date = params[:order][:date]
		@order.distance = params[:order][:distance]
		if @order.save
			flash[:notice] = "orden actualizada"
			redirect_to orders_path
		else
			render :edit
		end
	end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  def index
    @trucks = Truck.all
  end
  def new
    @truck = Truck.new
  end
  def edit
    @truck = Truck.find params[:id]
  end
  def Create
    @truck = Truck.new
    @truck.brand = params[:truck][:brand]
    @truck.year = params[:truck][:year]
    @truck.specs = params[:truck][:specs]
    @truck.avaible_days = params[:truck][:avaible_days]
    @truck.cost_x_km = params[:truck][:cost_x_km]

    if @truck.save
      redirect_to trucks_path
    else
      render :new
  end

  def update
    @truck = Truck.find params[:id]
    @truck.brand = params[:truck][:brand]
    @truck.year = params[:truck][:year]
    @truck.specs = params[:truck][:specs]
    @truck.avaible_days = params[:truck][:avaible_days]
    @truck.cost_x_km = params[:truck][:cost_x_km]

    if @truck.save
      redirect_to trucks_path
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/contactos/edit.html.haml
=form_for @contacto do |c|
  =c.label :nombre
  =c.text_field :nombre
  %br
  =c.label :apellido
  =c.text_field :apellido
  %br
  =c.label :telefono
  =c.text_field :telefono
  %br
  =c.label :correoElectronico
  =c.text_field :correoElectronico
  %br
  =c.label :direccion
  =c.text_field :direccion
  %br
  =c.submit

app/views/contactos/index.html.haml
= flash[:notice]
%table.some{:border => 1}
  - @contactos.each do |c|
    %tr
      %td
        =c.nombre
      %td
        =c.apellido
      %td
        =c.telefono
      %td
        =c.correoElectronico
      %td
        =c.direccion
      %td
        %a{ href: -edit_contacto_path(c)}
          %p editar
%a{ href: -new_contacto_path}
  %p crear

app/views/contactos/new.html.haml
=form_for @contacto do |c|
  =c.label :nombre
  =c.text_field :nombre
  %br
  =c.label :apellido
  =c.text_field :apellido
  %br
  =c.label :telefono
  =c.text_field :telefono
  %br
  =c.label :correoElectronico
  =c.text_field :correoElectronico
  %br
  =c.label :direccion
  =c.text_field :direccion
  %br
  =c.submit

app/views/empleados/edit.html.haml
=form_for @empleado do |f|
  =f.label :nombre
  =f.text_field :nombre
  %br
  =f.label :apellido
  =f.text_field :apellido
  %br
  =f.label :genero
  =f.select(:genero, [['Masculino'], ['Femenino']])
  %br
  =f.label :telefono
  =f.text_field :telefono
  %br
  =f.label :numeroDocumento
  =f.text_field :numeroDocumento
  %br
  =f.submit

app/views/empleados/index.html.haml
= flash[:notice]
%table.some{:border => 1}
  - @empleados.each do |c|
    %tr
      %td
        =c.nombre
      %td
        =c.apellido
      %td
        =c.genero
      %td
        =c.telefono
      %td
        =c.numeroDocumento
      %td
        %a{ href: -edit_empleado_path(c)}
          %p editar
%a{ href: -new_empleado_path}
  %p crear empleado

app/views/empleados/new.html.haml
=form_for @empleado do |f|
  =f.label :nombre
  =f.text_field :nombre
  %br
  =f.label :apellido
  =f.text_field :apellido
  %br
  =f.label :genero
  =f.select(:genero, [['Masculino'], ['Femenino']])
  %br
  =f.label :telefono
  =f.text_field :telefono
  %br
  =f.label :numeroDocumento
  =f.text_field :numeroDocumento
  %br
  =f.submit

app/views/empresas/edit.html.haml
=form_for @empresa do |f|
  =f.label :razonSocial
  =f.text_field :razonSocial
  %br
  =f.label :nit
  =f.text_field :nit
  %br
  =f.label :direccion
  =f.text_field :direccion
  %br
  =f.label :telefono
  =f.text_field :telefono
  %br
  =f.label :fax
  =f.text_field :fax
  %br
  =f.label :sitioWeb
  =f.text_field :sitioWeb
  %br
  =f.submit

app/views/empresas/index.html.haml
= flash[:notice]
%table.some{:border => 1}
  - @empresas.each do |c|
    %tr
      %td
        =c.razonSocial
      %td
        =c.nit
      %td
        =c.direccion
      %td
        =c.telefono
      %td
        =c.fax
      %td
        =c.sitioWeb
      %td
        %a{ href: -edit_empresa_path(c)}
          %p editar
%a{ href: -new_empresa_path}
  %p crear

app/views/empresas/new.html.haml
=form_for @empresa do |f|
  =f.label :razonSocial
  =f.text_field :razonSocial
  %br
  =f.label :nit
  =f.text_field :nit
  %br
  =f.label :direccion
  =f.text_field :direccion
  %br
  =f.label :telefono
  =f.text_field :telefono
  %br
  =f.label :fax
  =f.text_field :fax
  %br
  =f.label :sitioWeb
  =f.text_field :sitioWeb
  %br
  =f.submit

app/views/orders/edit.html.erb
<%= form_for @order do |f| %>
	<%= f.label  :date %>
	<%= f.text_field :date %>
	<%= f.label  :distance %>
	<%= f.number_field :distance %>
  <br>
  <h1>informacion de la evaluacion</h1>
    <%= fields_for :evaluation, @order.evaluation do |eval|%>
      description: <%=eval.text_field :description%>
      <br>
      note: <%= eval.number_field :note %>
    <% end %>
	<%= f.submit %>
<% end %>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<%= flash[:notice] %>
<table border = 1>
<% @orders.each do |order| %>
	<tr>
		<td><%= order.customer_id %></td>
		<td><%= order.truck_id %></td>
		<td><%= order.date %></td>
		<td><%= order.distance %></td>
		<td><a href= <%=edit_order_path(order) %>>editar</a></td>
	</tr>
<% end %> 
</table>
</body>
</html>

app/views/orders/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<%= form_for @order do |f| %>
	<%=f.label :customer %>
	<%=f.text_field :customer_id %>
	<br>
	<%=f.label :truck_id %>
	<%=f.text_field :truck_id%>
	<br>
	<%=f.label :date %>
	<%=f.text_field :date %>
	<br>
	<%=f.label :distance %>
	<%=f.text_field :distance %>
  <br>
  <h1>informacion de la evaluacion</h1>
    <%= fields_for :evaluation, @order.evaluation do |eval|%>
      description: <%=eval.text_field :description%>
      <br>
      note: <%= eval.number_field :note %>
    <% end %>
	<%= f.submit %>
	<% end %>
</body>
</html>

app/views/trucks/edit.html.haml
=form_for @truck do |f|
  =f.label :brand
  =f.text_field :brand
  %br
  =f.label :year
  =f.number_field :year
  %br
  =f.label :specs
  =f.text_field :specs
  %br
  =f.label :avaible_days
  =f.text_field :avaible_days
  %br
  =f.label :cost_x_km
  =f.number_field :cost_x_km
  %br
  =f.submit

app/views/trucks/index.html.haml
%table.some{:border => 1}
  - @contactos.each do |c|
    %tr
      %td
        =c.brand
      %td
        =c.year
      %td
        =c.specs
      %td
        =c.avaible_days
      %td
        =c.cost_x_km
      %td
        %a{ href: -edit_truck_path(c)}
          %p editar
%a{ href: -edit_truck_path}
  %p crear

app/views/trucks/new.html.haml
=form_for @truck do |f|
  =f.label :brand
  =f.text_field :brand
  %br
  =f.label :year
  =f.number_field :year
  %br
  =f.label :specs
  =f.text_field :specs
  %br
  =f.label :avaible_days
  =f.text_field :avaible_days
  %br
  =f.label :cost_x_km
  =f.number_field :cost_x_km
  %br
  =f.submit